name: angular_ui
version: 0.2.2
authors:
- Sergey Akopkokhyants <akserg@gmail.com>
- Tonis Pool <tonis.pool@gmail.com>
- Gunter Zochbauer <gzoechi@gmail.com>
- Francesco Cina <ufoscout@gmail.com>
description: Port of Angular-UI to Dart.
homepage: http://akserg.github.io/angular.dart.ui
environment:
  sdk: '>=1.1.1 <2.0.0'
dependencies:
  angular:
    git: 'https://github.com/akserg/angular.dart.ui.git'
  browser: '>=0.9.1'
  js: '>=0.2.2'
  logging_handlers: '>=0.8.0'
dev_dependencies:
  unittest: '>=0.10.0'
